defaultQuestion:
  qid: 2
  question: 'The default question'
  text: 'This is the default note for the demo application'
  choice: "choice1;choice2"
  CA: 3

assets:
  overrides:
    /: ../frontend/

server:
  rootPath: '/api/*'


database:
      #the name of db, h2 in our case
      driverClass: org.h2.Driver
      #username
      user: sa
      #password
      password:
      #JDBC URL

      url: jdbc:h2:~/fear

